version: "3.1"
services:
  postgres:
    image: postgres:12.4-alpine  
    restart: always
    container_name: postgres-ent
    ports:
      - 5432:5432
    volumes:
      - /data/sonarqube-ent/postgres/postgresql:/var/lib/postgresql
      - /data/sonarqube-ent/postgres/data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar

  sonar:
    image: sonarqube:9.9.0-enterprise 
    container_name: sonar-ent
    depends_on:
      - postgres
    volumes:
      - /data/sonarqube-ent/sonarqube/extensions:/opt/sonarqube/extensions
      - /data/sonarqube-ent/sonarqube/logs:/opt/sonarqube/logs
      - /data/sonarqube-ent/sonarqube/data:/opt/sonarqube/data
      - /data/sonarqube-ent/sonarqube/conf:/opt/sonarqube/conf
    ports:
      - 9000:9000
    command:
      - -Dsonar.ce.javaOpts=-Xmx2048m -javaagent:/opt/sonarqube/conf/SonarQubeAgent-1.2-SNAPSHOT.jar
      - -Dsonar.web.javaOpts=-Xmx2048m -javaagent:/opt/sonarqube/conf/SonarQubeAgent-1.2-SNAPSHOT.jar
   #   - -Dsonar.web.context=/sonar
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql-ent://postgres:5432/sonar
