apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hotwheel.backend.fullname" . }}
  labels:
    {{- include "hotwheel.labels" . | nindent 4 }}
    app: {{ include "hotwheel.backend.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hotwheel.selectorLabels" . | nindent 6 }}
      app: {{ include "hotwheel.backend.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hotwheel.selectorLabels" . | nindent 8 }}
        app: {{ include "hotwheel.backend.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hotwheel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "hotwheel.backend.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_DRUID_MASTER_URL
              value: {{ required "A valid .Values.config.database_url entry required!" .Values.config.database_url }}
            - name: SPRING_DATASOURCE_DRUID_MASTER_USERNAME
              value: {{ .Values.config.database_username }}
            - name: SPRING_DATASOURCE_DRUID_MASTER_PASSWORD
              value: {{ .Values.config.database_password }}
            - name: CI_ADMIN-DOMAIN
              value: {{ .Values.config.app_backend_url }}
            - name: CI_FRONT-DOMAIN
              value: {{ .Values.config.app_ui_url }}
            - name: SPRING_REDIS_HOST
              value: {{ .Values.config.redis.host}}
            - name: SPRING_REDIS_PORT
              value: {{ .Values.config.redis.port}}
            - name: SPRING_REDIS_PASSWORD
              value: {{ .Values.config.redis.password}}
            - name: SPRING_LDAP_URLS
              value: {{ required "A valid .Values.config.ldap.urls entry required!" .Values.config.ldap.urls}}
            - name: SPRING_LDAP_USERNAME
              value: {{ required "A valid .Values.config.ldap.username entry required!" .Values.config.ldap.username}}
            - name: SPRING_LDAP_PASSWORD
              value: {{ required "A valid .Values.config.ldap.password entry required!" .Values.config.ldap.password}}
            - name: SPRING_LDAP_BASE
              value: {{ required "A valid .Values.config.ldap.base entry required!" .Values.config.ldap.base}}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
